-- Seed: базовый каталог упражнений (fallback если ExerciseDB недоступен)
-- source = 'seed', минимально необходимый набор упражнений

INSERT OR IGNORE INTO exercise_catalog
  (source, source_exercise_id, name_en, name_ru, target, equipment, body_part, instructions_en)
VALUES
  ('seed','s001','Barbell Bench Press','Жим штанги лёжа','pectorals','barbell','chest',
   'Lie on bench. Grip bar slightly wider than shoulder-width. Lower to chest, press up.'),
  ('seed','s002','Pull-Up','Подтягивания','lats','body weight','back',
   'Hang from bar, palms forward. Pull chest to bar, lower slowly.'),
  ('seed','s003','Barbell Squat','Приседания со штангой','quads','barbell','upper legs',
   'Bar on traps. Squat until thighs parallel, drive up through heels.'),
  ('seed','s004','Deadlift','Становая тяга','glutes','barbell','upper legs',
   'Stand hip-width, grip bar. Keep back straight, drive hips forward to stand.'),
  ('seed','s005','Overhead Press','Жим над головой','delts','barbell','shoulders',
   'Press bar from shoulder height overhead, lock out arms.'),
  ('seed','s006','Barbell Row','Тяга штанги в наклоне','upper back','barbell','back',
   'Hinge forward, pull bar to lower chest, squeeze shoulder blades.'),
  ('seed','s007','Dumbbell Curl','Сгибание с гантелями','biceps','dumbbell','upper arms',
   'Stand, curl dumbbells to shoulders, lower slowly.'),
  ('seed','s008','Tricep Pushdown','Разгибание трицепса','triceps','cable','upper arms',
   'Hold cable bar, push down until arms straight, control the return.'),
  ('seed','s009','Leg Press','Жим ногами','quads','machine','upper legs',
   'Sit on machine, place feet shoulder-width. Press platform until nearly straight.'),
  ('seed','s010','Plank','Планка','core','body weight','waist',
   'Hold push-up position on forearms, body straight, core tight.'),
  ('seed','s011','Dumbbell Lateral Raise','Разведение гантелей','delts','dumbbell','shoulders',
   'Raise dumbbells to sides until parallel to floor, lower slowly.'),
  ('seed','s012','Romanian Deadlift','Румынская тяга','hamstrings','barbell','upper legs',
   'Hip hinge forward, lower bar along legs until hamstrings stretch, return.'),
  ('seed','s013','Cable Fly','Разведение в кроссовере','pectorals','cable','chest',
   'Pull cables in arc to meet in front of chest, squeeze pecs.'),
  ('seed','s014','Leg Curl','Сгибание ног в тренажёре','hamstrings','machine','upper legs',
   'Lie prone, curl legs toward glutes, lower slowly.'),
  ('seed','s015','Calf Raise','Подъём на носки','calves','body weight','lower legs',
   'Stand on edge, raise heels as high as possible, lower below platform.'),
  ('seed','s016','Face Pull','Тяга к лицу','traps','cable','shoulders',
   'Pull rope to face level, elbows flared, squeeze rear delts.'),
  ('seed','s017','Dip','Отжимания на брусьях','triceps','body weight','upper arms',
   'Support on bars, lower until shoulders below elbows, press back up.'),
  ('seed','s018','Incline Dumbbell Press','Жим гантелей на наклонной','pectorals','dumbbell','chest',
   'On incline bench press dumbbells up from chest level.'),
  ('seed','s019','Lat Pulldown','Тяга верхнего блока','lats','cable','back',
   'Pull bar to upper chest, elbows pointing down, control up.'),
  ('seed','s020','Hip Thrust','Ягодичный мост','glutes','barbell','upper legs',
   'Bar across hips, drive hips up until body straight, squeeze glutes.');
